apiVersion: v1
kind: Service
metadata:
  name: devops-prod-api-app-service
  labels:
    app: devops-prod-api-app
spec:
  selector:
    app: devops-prod-api-app
  ports:
    - protocol: TCP
      port: 3000 # service port
      targetPort: 3000 # container port
  type: NodePort # change to load balancer if running in cloud
